### ISSUE TITLE
Null Handling

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/settings#6]
Your latest commit points out a problem in the current flow: settings with `null` values. I think this will be a frequent enough need with Config handling that it will merit handling explicitly (maybe types will help?). Handlers should be able to:
* Handle a `set()` request to store an overriding `null` value
* Differentiate "no handler value" that should percolate from an actual `null` value response from `get()` requests that should stop

The service and helper will need updating to accommodate these parameters.

**Comment by lonnieezell** [comment]
I scanned through all of the config files in CodeIgniter and only 3 files had null values: `ContentSecurityPolicy`, `Email`, and `Kint`.  All of those _could_ be handled with empty strings, though obviously we wouldn't want to do that now. 

My point, though, is that I don't think null values would be used all that much - forgetting the saved setting and letting it revert back to it's original (or saving an empty string/boolean false) would be much more common. 

My thinking here is: 

1. The `settting()` helper method stays the same. Converting that to work with a null value (which currently is how it knows whether it's getting or setting) would be more trouble than it seems to be worth. 
2. Ensure that the `set()` method on the `Settings` class can handle null values so that if someone truly needs it, they can always do it with: `setting()->set('foo', null);`

Thoughts?

**Comment by MGatner** [comment]
I would still push for full `null` compliance. I think much of the framework has not handled nullables very well, and they will only get more important once we drop `7.3` since we will be able to add actual types to everything. Things like `Logger` Config using this is poor:
```php
   * Note: Leaving it blank will default to 'log'.
   */
  'fileExtension' => '',
```

Even if null values aren't common in the framework they are in libraries. I personally use them heavily; Myth:Auth uses them at very key control points. Empowering these from the library but not the helper seems unduly punishing.

**Comment by MGatner** [comment]
I think the helper would actually be an easy fix using `func_get_args()`: https://3v4l.org/L2ATH

I can work on a PR if you are amenable to head this direction.

**Comment by lonnieezell** [comment]
Oh, interesting, I didn't realize that would work. I guess it makes sense, but I thought with the default being null it wouldn't recognize. Cool. The only other way I was thinking would work well would be another class to represent null, or something, which seemed pretty ugly.

Yes, I'm good with that approach.
